services:
  redis-7000:
    image: redis:7.2-alpine
    container_name: redis-7000
    command: >
      sh -c "redis-server
      --port 7000
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --appendonly yes
      --cluster-announce-hostname redis-7000
      --cluster-announce-port 7000
      --cluster-announce-bus-port 17000"
    ports: ["7000:7000","17000:17000"]